version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainbuzz-api
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - brainbuzz-network

  # NGINX service for reverse proxy and CORS handling
  nginx:
    image: nginx:alpine
    container_name: brainbuzz-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - brainbuzz-network

  # Certbot service for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: brainbuzz-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d your-backend-domain.com --agree-tos
    depends_on:
      - nginx

networks:
  brainbuzz-network:
    driver: bridge